### PR TITLE
Don't fill where fill is "none"

### PR DESCRIPTION
**Pull request by kengorab**
This addresses #39. The pink up arrow which I included as the expected value was produced by this code.

### CODE REVIEW

**Comment by kengorab** [comment]
I also had to fix the build, since it was failing for me. I added `babel-core` and some babel presets as devDependencies, so they'd be installed when running `npm install`, and added a `.babelrc` file which `babel-core` will use when it's registered when running `npm test`. There were also 2 failing tests which I fixed as well (I'm assuming the signature of the `utils/transformStyle` function changed at one point from accepting an object to accepting 3 params, and the tests were never updated?).

**Comment by JanErikFoss** [comment]
Good job, looking forward to this being merged

**Comment by kengorab** [comment]
So I suppose it was a good thing this wasn't merged immediately, since I uncovered a bug that I introduced by adding a `.babelrc` file which referenced babel-presets that were only installed as devDependencies. Since we only need to run babel for testing, I opted to use a test-helper for mocha, which runs `babel-core/register` and passes in the presets, rather than use the `.babelrc` approach.

I've verified that this works when installed into another application.

**Comment by kengorab** [comment]
@matc4 Any idea when this pull request could be reviewed?

**Comment by matc4** [comment]
Hello @kengorab , Can you modify the pull so only index.js is modified? thanks

**Comment by kengorab** [comment]
Should I split this up into 2 pull requests, one fixing the tests and another for the actual code change? Aside from the accidentally added `.idea` directory (which I've just now realized I committed), the other changes were made in order to fix the build.

**Comment by matc4** [comment]
Ok, then remove only the idea part.
Thanks!

**Comment by kengorab** [comment]
Will do! I'll put up the changes tonight.

**Comment by matc4** [comment]
Changes included. Thanks @kengorab !

**Pull request closed without merging**
